# docker-compose.yml
version: '3.8'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"